name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Features & Enhancements'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'documentation'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/jensenbox/ha-arctic-spa/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
